### PR TITLE
implements proposed protocol #11

### LINKED ISSUE #11: Design a protocol for listing/changing levels across all playbacks
It makes possible to work across all the playbacks (hls, flashls, dash, rtmp, html5...) that follows this protocol.

## Listing levels
* playback must triggers`PLAYBACK_LEVELS_AVAILABLE` with an ordered array of levels `[{id: 3, label: '500Kbps'}, {id: 4, label: '600Kpbs'}]`
* to have a property `levels`, initialized with `[]` and then after filled with all levels
* we mustn't render when there is no level
* think about i18n
* update README describing what is needed for your playback to use this plugin

## Changing level
* add property (set/get) to playback `playback.currentLevel = id`
* optionally triggers events: `PLAYBACK_LEVEL_SWITCH_START` and `PLAYBACK_LEVEL_SWITCH_END`

## Clappr's work
* add this event to clappr

## Misc
* `id=-`1 being always the `Auto` options

@flavioribeiro 's idea

### PR DESCRIPTION
**Pull request by leandromoreira**
### We need to publish a new version (with fixes) before this merge

Fixes #11

### CODE REVIEW

**Comment by leandromoreira** [comment]
I tested it locally with `DashShakaPlayback` and it worked but I had to: 
* add properties: levels and currentLevel
* triggers `this.trigger(Events.PLAYBACK_LEVELS_AVAILABLE, this.levels)`

**We'll need to do that too for hls/flashl/rmtp**


```diff
diff --git a/index.js b/index.js
index 677a450..265cd90 100644
--- a/index.js
+++ b/index.js
@@ -2,15 +2,28 @@ import {HTML5Video, Log, Events} from 'clappr'
 import shaka from 'shaka-player'
 
 const SEND_STATS_AT = 30 * 1000
+const AUTO = -1
 
 export default class DashShakaPlayback extends HTML5Video {
   get name() {return 'dash_shaka_playback'}
 
   get shakaVersion() {return shaka.player.Player.version}
 
+  get levels() { return this._levels }
+
+  set currentLevel(id) {
+    this._currentLevelId = id
+    var isAuto = this._currentLevelId === AUTO
+
+    this._player.configure({enableAdaptation: isAuto})
+    !isAuto && this.selectVideoTrack(this._currentLevelId)
+  }
+  get currentLevel() { return this._currentLevelId || AUTO }
+
   constructor(options) {
     super(options)
     this._readyToPlay = false
+    this._levels = []
 
     var checkIfIsReady = (fn) => {
       return (arg) => {
@@ -87,6 +100,15 @@ export default class DashShakaPlayback extends HTML5Video {
   _loaded() {
     this._ready()
     this._startToSendStats()
+    this._levels = this._fillLevels()
+    this.trigger(Events.PLAYBACK_LEVELS_AVAILABLE, this.levels)
+  }
+
+  _fillLevels() {
+    var levels = []
+    this.videoTracks().forEach((videoTrack) => levels.push({id: videoTrack.id, label: videoTrack.height}))
+
+    return levels
   }
 
   _startToSendStats() {

```

**Comment by flavioribeiro** [comment]
it LGTM, do you have plans to bump a new version before we merge this?

**Comment by towerz** [comment]
Looks good to me as well.

**Comment by leandromoreira** [comment]
@flavioribeiro I already did it, we're good to merge. :) thanks

**Pull request merged**
